/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Marianne
 */
public class FoodDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form FoodDashBoard
     */
    public FoodDashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Food2 = new javax.swing.JPanel();
        CoffeeName = new javax.swing.JLabel();
        CoffeePrice = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        coffeeName = new javax.swing.JLabel();
        coffeePrice = new javax.swing.JLabel();
        CoffeSize = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        Item1 = new javax.swing.JCheckBox();
        CoffeeImage1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SmallSize = new javax.swing.JCheckBox();
        MediumSize = new javax.swing.JCheckBox();
        LargeSize = new javax.swing.JCheckBox();
        ExtraLarge = new javax.swing.JCheckBox();
        Food1 = new javax.swing.JPanel();
        CoffeeName1 = new javax.swing.JLabel();
        CoffeePrice1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        coffeeName1 = new javax.swing.JLabel();
        coffeePrice1 = new javax.swing.JLabel();
        CoffeSize1 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        Item2 = new javax.swing.JCheckBox();
        CoffeeImage2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        SmallSize1 = new javax.swing.JCheckBox();
        MediumSize1 = new javax.swing.JCheckBox();
        LargeSize1 = new javax.swing.JCheckBox();
        ExtraLarge1 = new javax.swing.JCheckBox();
        Food3 = new javax.swing.JPanel();
        CoffeeName2 = new javax.swing.JLabel();
        CoffeePrice2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        coffeeName2 = new javax.swing.JLabel();
        coffeePrice2 = new javax.swing.JLabel();
        CoffeSize2 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        Item3 = new javax.swing.JCheckBox();
        CoffeeImage3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        SmallSize2 = new javax.swing.JCheckBox();
        MediumSize2 = new javax.swing.JCheckBox();
        LargeSize2 = new javax.swing.JCheckBox();
        ExtraLarge2 = new javax.swing.JCheckBox();
        Food4 = new javax.swing.JPanel();
        CoffeeName3 = new javax.swing.JLabel();
        CoffeePrice3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        coffeeName3 = new javax.swing.JLabel();
        coffeePrice3 = new javax.swing.JLabel();
        CoffeSize3 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        Item4 = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        SmallSize3 = new javax.swing.JCheckBox();
        MediumSize3 = new javax.swing.JCheckBox();
        LargeSize3 = new javax.swing.JCheckBox();
        ExtraLarge3 = new javax.swing.JCheckBox();
        CoffeeImage4 = new javax.swing.JLabel();
        Food5 = new javax.swing.JPanel();
        CoffeeName4 = new javax.swing.JLabel();
        CoffeePrice4 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        coffeeName4 = new javax.swing.JLabel();
        coffeePrice4 = new javax.swing.JLabel();
        CoffeSize4 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        Item5 = new javax.swing.JCheckBox();
        CoffeeImage5 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        SmallSize4 = new javax.swing.JCheckBox();
        MediumSize4 = new javax.swing.JCheckBox();
        LargeSize4 = new javax.swing.JCheckBox();
        ExtraLarge4 = new javax.swing.JCheckBox();
        Food6 = new javax.swing.JPanel();
        CoffeeName6 = new javax.swing.JLabel();
        CoffeePrice6 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        coffeeName6 = new javax.swing.JLabel();
        coffeePrice6 = new javax.swing.JLabel();
        CoffeSize6 = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        Item7 = new javax.swing.JCheckBox();
        CoffeeImage7 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        SmallSize6 = new javax.swing.JCheckBox();
        MediumSize6 = new javax.swing.JCheckBox();
        LargeSize6 = new javax.swing.JCheckBox();
        ExtraLarge6 = new javax.swing.JCheckBox();
        Food7 = new javax.swing.JPanel();
        CoffeeName7 = new javax.swing.JLabel();
        CoffeePrice7 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        coffeeName7 = new javax.swing.JLabel();
        coffeePrice7 = new javax.swing.JLabel();
        CoffeSize7 = new javax.swing.JLabel();
        jSpinner8 = new javax.swing.JSpinner();
        Item8 = new javax.swing.JCheckBox();
        CoffeeImage8 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        SmallSize7 = new javax.swing.JCheckBox();
        MediumSize7 = new javax.swing.JCheckBox();
        LargeSize7 = new javax.swing.JCheckBox();
        ExtraLarge7 = new javax.swing.JCheckBox();
        Food8 = new javax.swing.JPanel();
        CoffeeName8 = new javax.swing.JLabel();
        CoffeePrice8 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        coffeeName8 = new javax.swing.JLabel();
        coffeePrice8 = new javax.swing.JLabel();
        CoffeSize8 = new javax.swing.JLabel();
        jSpinner9 = new javax.swing.JSpinner();
        Item9 = new javax.swing.JCheckBox();
        CoffeeImage9 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        SmallSize8 = new javax.swing.JCheckBox();
        MediumSize8 = new javax.swing.JCheckBox();
        LargeSize8 = new javax.swing.JCheckBox();
        ExtraLarge8 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(203, 183, 153));

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        CoffeeName.setText("Name:");

        CoffeePrice.setText("Price");

        jLabel3.setText("Quantity");

        jLabel2.setText("Purchase");

        coffeeName.setText("Americano");

        coffeePrice.setText("Php: 69");

        CoffeSize.setText("Size");

        CoffeeImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/Americano.jpg"))); // NOI18N

        jLabel4.setText("Small");

        jLabel5.setText("Medium");

        jLabel6.setText("Large");

        jLabel7.setText("Extra Large");

        SmallSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallSizeActionPerformed(evt);
            }
        });

        ExtraLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtraLargeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Food2Layout = new javax.swing.GroupLayout(Food2);
        Food2.setLayout(Food2Layout);
        Food2Layout.setHorizontalGroup(
            Food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Food2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Food2Layout.createSequentialGroup()
                        .addGroup(Food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Food2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Item1))
                            .addGroup(Food2Layout.createSequentialGroup()
                                .addComponent(CoffeSize)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Food2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SmallSize))
                                    .addGroup(Food2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LargeSize)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Food2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MediumSize))
                            .addGroup(Food2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ExtraLarge))))
                    .addGroup(Food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Food2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSpinner1))
                        .addGroup(Food2Layout.createSequentialGroup()
                            .addGroup(Food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CoffeeName)
                                .addComponent(CoffeePrice))
                            .addGap(18, 18, 18)
                            .addGroup(Food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(coffeePrice)
                                .addComponent(coffeeName)))))
                .addGap(18, 18, 18))
            .addComponent(CoffeeImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        Food2Layout.setVerticalGroup(
            Food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Food2Layout.createSequentialGroup()
                .addComponent(CoffeeImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoffeeName)
                    .addComponent(coffeeName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoffeePrice)
                    .addComponent(coffeePrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Food2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CoffeSize)
                            .addComponent(jLabel4)))
                    .addGroup(Food2Layout.createSequentialGroup()
                        .addComponent(Item1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MediumSize)
                            .addComponent(jLabel5)
                            .addComponent(SmallSize))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Food2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(LargeSize)
                    .addComponent(jLabel7)
                    .addComponent(ExtraLarge))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        CoffeeName1.setText("Name:");

        CoffeePrice1.setText("Price");

        jLabel8.setText("Quantity");

        jLabel9.setText("Purchase");

        coffeeName1.setText("Americano");

        coffeePrice1.setText("Php: 69");

        CoffeSize1.setText("Size");

        CoffeeImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/Americano.jpg"))); // NOI18N

        jLabel10.setText("Small");

        jLabel11.setText("Medium");

        jLabel12.setText("Large");

        jLabel13.setText("Extra Large");

        SmallSize1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallSize1ActionPerformed(evt);
            }
        });

        ExtraLarge1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtraLarge1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Food1Layout = new javax.swing.GroupLayout(Food1);
        Food1.setLayout(Food1Layout);
        Food1Layout.setHorizontalGroup(
            Food1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Food1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Food1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Food1Layout.createSequentialGroup()
                        .addGroup(Food1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Food1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Item2))
                            .addGroup(Food1Layout.createSequentialGroup()
                                .addComponent(CoffeSize1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Food1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Food1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SmallSize1))
                                    .addGroup(Food1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LargeSize1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Food1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Food1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MediumSize1))
                            .addGroup(Food1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ExtraLarge1))))
                    .addGroup(Food1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Food1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSpinner2))
                        .addGroup(Food1Layout.createSequentialGroup()
                            .addGroup(Food1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CoffeeName1)
                                .addComponent(CoffeePrice1))
                            .addGap(18, 18, 18)
                            .addGroup(Food1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(coffeePrice1)
                                .addComponent(coffeeName1)))))
                .addGap(18, 18, 18))
            .addComponent(CoffeeImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        Food1Layout.setVerticalGroup(
            Food1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Food1Layout.createSequentialGroup()
                .addComponent(CoffeeImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoffeeName1)
                    .addComponent(coffeeName1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoffeePrice1)
                    .addComponent(coffeePrice1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Food1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Food1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CoffeSize1)
                            .addComponent(jLabel10)))
                    .addGroup(Food1Layout.createSequentialGroup()
                        .addComponent(Item2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Food1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MediumSize1)
                            .addComponent(jLabel11)
                            .addComponent(SmallSize1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Food1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(LargeSize1)
                    .addComponent(jLabel13)
                    .addComponent(ExtraLarge1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        CoffeeName2.setText("Name:");

        CoffeePrice2.setText("Price");

        jLabel14.setText("Quantity");

        jLabel15.setText("Purchase");

        coffeeName2.setText("Americano");

        coffeePrice2.setText("Php: 69");

        CoffeSize2.setText("Size");

        CoffeeImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/Americano.jpg"))); // NOI18N

        jLabel16.setText("Small");

        jLabel17.setText("Medium");

        jLabel18.setText("Large");

        jLabel19.setText("Extra Large");

        SmallSize2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallSize2ActionPerformed(evt);
            }
        });

        ExtraLarge2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtraLarge2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Food3Layout = new javax.swing.GroupLayout(Food3);
        Food3.setLayout(Food3Layout);
        Food3Layout.setHorizontalGroup(
            Food3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Food3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Food3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Food3Layout.createSequentialGroup()
                        .addGroup(Food3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Food3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Item3))
                            .addGroup(Food3Layout.createSequentialGroup()
                                .addComponent(CoffeSize2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Food3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Food3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SmallSize2))
                                    .addGroup(Food3Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LargeSize2)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Food3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Food3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MediumSize2))
                            .addGroup(Food3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ExtraLarge2))))
                    .addGroup(Food3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Food3Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSpinner3))
                        .addGroup(Food3Layout.createSequentialGroup()
                            .addGroup(Food3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CoffeeName2)
                                .addComponent(CoffeePrice2))
                            .addGap(18, 18, 18)
                            .addGroup(Food3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(coffeePrice2)
                                .addComponent(coffeeName2)))))
                .addGap(18, 18, 18))
            .addComponent(CoffeeImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        Food3Layout.setVerticalGroup(
            Food3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Food3Layout.createSequentialGroup()
                .addComponent(CoffeeImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoffeeName2)
                    .addComponent(coffeeName2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoffeePrice2)
                    .addComponent(coffeePrice2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Food3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Food3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CoffeSize2)
                            .addComponent(jLabel16)))
                    .addGroup(Food3Layout.createSequentialGroup()
                        .addComponent(Item3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Food3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MediumSize2)
                            .addComponent(jLabel17)
                            .addComponent(SmallSize2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Food3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(LargeSize2)
                    .addComponent(jLabel19)
                    .addComponent(ExtraLarge2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        CoffeeName3.setText("Name:");

        CoffeePrice3.setText("Price");

        jLabel20.setText("Quantity");

        jLabel21.setText("Purchase");

        coffeeName3.setText("Americano");

        coffeePrice3.setText("Php: 69");

        CoffeSize3.setText("Size");

        jLabel22.setText("Small");

        jLabel23.setText("Medium");

        jLabel24.setText("Large");

        jLabel25.setText("Extra Large");

        SmallSize3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallSize3ActionPerformed(evt);
            }
        });

        ExtraLarge3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtraLarge3ActionPerformed(evt);
            }
        });

        CoffeeImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/Americano.jpg"))); // NOI18N

        javax.swing.GroupLayout Food4Layout = new javax.swing.GroupLayout(Food4);
        Food4.setLayout(Food4Layout);
        Food4Layout.setHorizontalGroup(
            Food4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Food4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Food4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Food4Layout.createSequentialGroup()
                        .addGroup(Food4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Food4Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Item4))
                            .addGroup(Food4Layout.createSequentialGroup()
                                .addComponent(CoffeSize3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Food4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Food4Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SmallSize3))
                                    .addGroup(Food4Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LargeSize3)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Food4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Food4Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MediumSize3))
                            .addGroup(Food4Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ExtraLarge3))))
                    .addGroup(Food4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Food4Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSpinner4))
                        .addGroup(Food4Layout.createSequentialGroup()
                            .addGroup(Food4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CoffeeName3)
                                .addComponent(CoffeePrice3))
                            .addGap(18, 18, 18)
                            .addGroup(Food4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(coffeePrice3)
                                .addComponent(coffeeName3)))))
                .addGap(18, 18, 18))
            .addGroup(Food4Layout.createSequentialGroup()
                .addComponent(CoffeeImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        Food4Layout.setVerticalGroup(
            Food4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Food4Layout.createSequentialGroup()
                .addComponent(CoffeeImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoffeeName3)
                    .addComponent(coffeeName3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoffeePrice3)
                    .addComponent(coffeePrice3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Food4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Food4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CoffeSize3)
                            .addComponent(jLabel22)))
                    .addGroup(Food4Layout.createSequentialGroup()
                        .addComponent(Item4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Food4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MediumSize3)
                            .addComponent(jLabel23)
                            .addComponent(SmallSize3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Food4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(LargeSize3)
                    .addComponent(jLabel25)
                    .addComponent(ExtraLarge3))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        CoffeeName4.setText("Name:");

        CoffeePrice4.setText("Price");

        jLabel26.setText("Quantity");

        jLabel27.setText("Purchase");

        coffeeName4.setText("Americano");

        coffeePrice4.setText("Php: 69");

        CoffeSize4.setText("Size");

        CoffeeImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/Americano.jpg"))); // NOI18N

        jLabel28.setText("Small");

        jLabel29.setText("Medium");

        jLabel30.setText("Large");

        jLabel31.setText("Extra Large");

        SmallSize4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallSize4ActionPerformed(evt);
            }
        });

        ExtraLarge4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtraLarge4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Food5Layout = new javax.swing.GroupLayout(Food5);
        Food5.setLayout(Food5Layout);
        Food5Layout.setHorizontalGroup(
            Food5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Food5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Food5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Food5Layout.createSequentialGroup()
                        .addGroup(Food5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Food5Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Item5))
                            .addGroup(Food5Layout.createSequentialGroup()
                                .addComponent(CoffeSize4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Food5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Food5Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SmallSize4))
                                    .addGroup(Food5Layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LargeSize4)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Food5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Food5Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MediumSize4))
                            .addGroup(Food5Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ExtraLarge4))))
                    .addGroup(Food5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Food5Layout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSpinner5))
                        .addGroup(Food5Layout.createSequentialGroup()
                            .addGroup(Food5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CoffeeName4)
                                .addComponent(CoffeePrice4))
                            .addGap(18, 18, 18)
                            .addGroup(Food5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(coffeePrice4)
                                .addComponent(coffeeName4)))))
                .addGap(18, 18, 18))
            .addComponent(CoffeeImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        Food5Layout.setVerticalGroup(
            Food5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Food5Layout.createSequentialGroup()
                .addComponent(CoffeeImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoffeeName4)
                    .addComponent(coffeeName4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoffeePrice4)
                    .addComponent(coffeePrice4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Food5Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Food5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CoffeSize4)
                            .addComponent(jLabel28)))
                    .addGroup(Food5Layout.createSequentialGroup()
                        .addComponent(Item5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Food5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MediumSize4)
                            .addComponent(jLabel29)
                            .addComponent(SmallSize4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Food5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(LargeSize4)
                    .addComponent(jLabel31)
                    .addComponent(ExtraLarge4))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        CoffeeName6.setText("Name:");

        CoffeePrice6.setText("Price");

        jLabel38.setText("Quantity");

        jLabel39.setText("Purchase");

        coffeeName6.setText("Americano");

        coffeePrice6.setText("Php: 69");

        CoffeSize6.setText("Size");

        CoffeeImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/Americano.jpg"))); // NOI18N

        jLabel40.setText("Small");

        jLabel41.setText("Medium");

        jLabel42.setText("Large");

        jLabel43.setText("Extra Large");

        SmallSize6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallSize6ActionPerformed(evt);
            }
        });

        ExtraLarge6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtraLarge6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Food6Layout = new javax.swing.GroupLayout(Food6);
        Food6.setLayout(Food6Layout);
        Food6Layout.setHorizontalGroup(
            Food6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Food6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Food6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Food6Layout.createSequentialGroup()
                        .addGroup(Food6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Food6Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Item7))
                            .addGroup(Food6Layout.createSequentialGroup()
                                .addComponent(CoffeSize6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Food6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Food6Layout.createSequentialGroup()
                                        .addComponent(jLabel40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SmallSize6))
                                    .addGroup(Food6Layout.createSequentialGroup()
                                        .addComponent(jLabel42)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LargeSize6)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Food6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Food6Layout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MediumSize6))
                            .addGroup(Food6Layout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ExtraLarge6))))
                    .addGroup(Food6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Food6Layout.createSequentialGroup()
                            .addComponent(jLabel38)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSpinner7))
                        .addGroup(Food6Layout.createSequentialGroup()
                            .addGroup(Food6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CoffeeName6)
                                .addComponent(CoffeePrice6))
                            .addGap(18, 18, 18)
                            .addGroup(Food6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(coffeePrice6)
                                .addComponent(coffeeName6)))))
                .addGap(18, 18, 18))
            .addComponent(CoffeeImage7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        Food6Layout.setVerticalGroup(
            Food6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Food6Layout.createSequentialGroup()
                .addComponent(CoffeeImage7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoffeeName6)
                    .addComponent(coffeeName6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoffeePrice6)
                    .addComponent(coffeePrice6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jSpinner7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Food6Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Food6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CoffeSize6)
                            .addComponent(jLabel40)))
                    .addGroup(Food6Layout.createSequentialGroup()
                        .addComponent(Item7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Food6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MediumSize6)
                            .addComponent(jLabel41)
                            .addComponent(SmallSize6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Food6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(LargeSize6)
                    .addComponent(jLabel43)
                    .addComponent(ExtraLarge6))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        CoffeeName7.setText("Name:");

        CoffeePrice7.setText("Price");

        jLabel44.setText("Quantity");

        jLabel45.setText("Purchase");

        coffeeName7.setText("Americano");

        coffeePrice7.setText("Php: 69");

        CoffeSize7.setText("Size");

        CoffeeImage8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/Americano.jpg"))); // NOI18N

        jLabel46.setText("Small");

        jLabel47.setText("Medium");

        jLabel48.setText("Large");

        jLabel49.setText("Extra Large");

        SmallSize7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallSize7ActionPerformed(evt);
            }
        });

        ExtraLarge7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtraLarge7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Food7Layout = new javax.swing.GroupLayout(Food7);
        Food7.setLayout(Food7Layout);
        Food7Layout.setHorizontalGroup(
            Food7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Food7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Food7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Food7Layout.createSequentialGroup()
                        .addGroup(Food7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Food7Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Item8))
                            .addGroup(Food7Layout.createSequentialGroup()
                                .addComponent(CoffeSize7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Food7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Food7Layout.createSequentialGroup()
                                        .addComponent(jLabel46)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SmallSize7))
                                    .addGroup(Food7Layout.createSequentialGroup()
                                        .addComponent(jLabel48)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LargeSize7)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Food7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Food7Layout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MediumSize7))
                            .addGroup(Food7Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ExtraLarge7))))
                    .addGroup(Food7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Food7Layout.createSequentialGroup()
                            .addComponent(jLabel44)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSpinner8))
                        .addGroup(Food7Layout.createSequentialGroup()
                            .addGroup(Food7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CoffeeName7)
                                .addComponent(CoffeePrice7))
                            .addGap(18, 18, 18)
                            .addGroup(Food7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(coffeePrice7)
                                .addComponent(coffeeName7)))))
                .addGap(18, 18, 18))
            .addComponent(CoffeeImage8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        Food7Layout.setVerticalGroup(
            Food7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Food7Layout.createSequentialGroup()
                .addComponent(CoffeeImage8, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoffeeName7)
                    .addComponent(coffeeName7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoffeePrice7)
                    .addComponent(coffeePrice7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jSpinner8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Food7Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Food7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CoffeSize7)
                            .addComponent(jLabel46)))
                    .addGroup(Food7Layout.createSequentialGroup()
                        .addComponent(Item8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Food7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MediumSize7)
                            .addComponent(jLabel47)
                            .addComponent(SmallSize7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Food7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel48)
                    .addComponent(LargeSize7)
                    .addComponent(jLabel49)
                    .addComponent(ExtraLarge7))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        CoffeeName8.setText("Name:");

        CoffeePrice8.setText("Price");

        jLabel50.setText("Quantity");

        jLabel51.setText("Purchase");

        coffeeName8.setText("Americano");

        coffeePrice8.setText("Php: 69");

        CoffeSize8.setText("Size");

        CoffeeImage9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CoffeeImage/Americano.jpg"))); // NOI18N

        jLabel52.setText("Small");

        jLabel53.setText("Medium");

        jLabel54.setText("Large");

        jLabel55.setText("Extra Large");

        SmallSize8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallSize8ActionPerformed(evt);
            }
        });

        ExtraLarge8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtraLarge8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Food8Layout = new javax.swing.GroupLayout(Food8);
        Food8.setLayout(Food8Layout);
        Food8Layout.setHorizontalGroup(
            Food8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Food8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Food8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Food8Layout.createSequentialGroup()
                        .addGroup(Food8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Food8Layout.createSequentialGroup()
                                .addComponent(jLabel51)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Item9))
                            .addGroup(Food8Layout.createSequentialGroup()
                                .addComponent(CoffeSize8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Food8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Food8Layout.createSequentialGroup()
                                        .addComponent(jLabel52)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SmallSize8))
                                    .addGroup(Food8Layout.createSequentialGroup()
                                        .addComponent(jLabel54)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LargeSize8)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Food8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Food8Layout.createSequentialGroup()
                                .addComponent(jLabel53)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MediumSize8))
                            .addGroup(Food8Layout.createSequentialGroup()
                                .addComponent(jLabel55)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ExtraLarge8))))
                    .addGroup(Food8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Food8Layout.createSequentialGroup()
                            .addComponent(jLabel50)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSpinner9))
                        .addGroup(Food8Layout.createSequentialGroup()
                            .addGroup(Food8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CoffeeName8)
                                .addComponent(CoffeePrice8))
                            .addGap(18, 18, 18)
                            .addGroup(Food8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(coffeePrice8)
                                .addComponent(coffeeName8)))))
                .addGap(18, 18, 18))
            .addComponent(CoffeeImage9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        Food8Layout.setVerticalGroup(
            Food8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Food8Layout.createSequentialGroup()
                .addComponent(CoffeeImage9, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoffeeName8)
                    .addComponent(coffeeName8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoffeePrice8)
                    .addComponent(coffeePrice8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(jSpinner9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Food8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Food8Layout.createSequentialGroup()
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Food8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CoffeSize8)
                            .addComponent(jLabel52)))
                    .addGroup(Food8Layout.createSequentialGroup()
                        .addComponent(Item9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Food8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MediumSize8)
                            .addComponent(jLabel53)
                            .addComponent(SmallSize8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Food8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel54)
                    .addComponent(LargeSize8)
                    .addComponent(jLabel55)
                    .addComponent(ExtraLarge8))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Food1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Food4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Food2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(Food3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(Food6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Food5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(Food7, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Food8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Food1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(Food4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Food2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(Food5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Food3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Food6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Food7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Food8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel1.setText("Food Menu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(305, 305, 305))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExtraLarge7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtraLarge7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExtraLarge7ActionPerformed

    private void SmallSize7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallSize7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallSize7ActionPerformed

    private void ExtraLarge6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtraLarge6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExtraLarge6ActionPerformed

    private void SmallSize6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallSize6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallSize6ActionPerformed

    private void ExtraLarge4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtraLarge4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExtraLarge4ActionPerformed

    private void SmallSize4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallSize4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallSize4ActionPerformed

    private void ExtraLarge3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtraLarge3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExtraLarge3ActionPerformed

    private void SmallSize3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallSize3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallSize3ActionPerformed

    private void ExtraLarge2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtraLarge2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExtraLarge2ActionPerformed

    private void SmallSize2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallSize2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallSize2ActionPerformed

    private void ExtraLarge1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtraLarge1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExtraLarge1ActionPerformed

    private void SmallSize1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallSize1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallSize1ActionPerformed

    private void ExtraLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtraLargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExtraLargeActionPerformed

    private void SmallSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallSizeActionPerformed

    private void SmallSize8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallSize8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmallSize8ActionPerformed

    private void ExtraLarge8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtraLarge8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExtraLarge8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CoffeSize;
    private javax.swing.JLabel CoffeSize1;
    private javax.swing.JLabel CoffeSize2;
    private javax.swing.JLabel CoffeSize3;
    private javax.swing.JLabel CoffeSize4;
    private javax.swing.JLabel CoffeSize6;
    private javax.swing.JLabel CoffeSize7;
    private javax.swing.JLabel CoffeSize8;
    private javax.swing.JLabel CoffeeImage1;
    private javax.swing.JLabel CoffeeImage2;
    private javax.swing.JLabel CoffeeImage3;
    private javax.swing.JLabel CoffeeImage4;
    private javax.swing.JLabel CoffeeImage5;
    private javax.swing.JLabel CoffeeImage7;
    private javax.swing.JLabel CoffeeImage8;
    private javax.swing.JLabel CoffeeImage9;
    private javax.swing.JLabel CoffeeName;
    private javax.swing.JLabel CoffeeName1;
    private javax.swing.JLabel CoffeeName2;
    private javax.swing.JLabel CoffeeName3;
    private javax.swing.JLabel CoffeeName4;
    private javax.swing.JLabel CoffeeName6;
    private javax.swing.JLabel CoffeeName7;
    private javax.swing.JLabel CoffeeName8;
    private javax.swing.JLabel CoffeePrice;
    private javax.swing.JLabel CoffeePrice1;
    private javax.swing.JLabel CoffeePrice2;
    private javax.swing.JLabel CoffeePrice3;
    private javax.swing.JLabel CoffeePrice4;
    private javax.swing.JLabel CoffeePrice6;
    private javax.swing.JLabel CoffeePrice7;
    private javax.swing.JLabel CoffeePrice8;
    private javax.swing.JCheckBox ExtraLarge;
    private javax.swing.JCheckBox ExtraLarge1;
    private javax.swing.JCheckBox ExtraLarge2;
    private javax.swing.JCheckBox ExtraLarge3;
    private javax.swing.JCheckBox ExtraLarge4;
    private javax.swing.JCheckBox ExtraLarge6;
    private javax.swing.JCheckBox ExtraLarge7;
    private javax.swing.JCheckBox ExtraLarge8;
    private javax.swing.JPanel Food1;
    private javax.swing.JPanel Food2;
    private javax.swing.JPanel Food3;
    private javax.swing.JPanel Food4;
    private javax.swing.JPanel Food5;
    private javax.swing.JPanel Food6;
    private javax.swing.JPanel Food7;
    private javax.swing.JPanel Food8;
    private javax.swing.JCheckBox Item1;
    private javax.swing.JCheckBox Item2;
    private javax.swing.JCheckBox Item3;
    private javax.swing.JCheckBox Item4;
    private javax.swing.JCheckBox Item5;
    private javax.swing.JCheckBox Item7;
    private javax.swing.JCheckBox Item8;
    private javax.swing.JCheckBox Item9;
    private javax.swing.JCheckBox LargeSize;
    private javax.swing.JCheckBox LargeSize1;
    private javax.swing.JCheckBox LargeSize2;
    private javax.swing.JCheckBox LargeSize3;
    private javax.swing.JCheckBox LargeSize4;
    private javax.swing.JCheckBox LargeSize6;
    private javax.swing.JCheckBox LargeSize7;
    private javax.swing.JCheckBox LargeSize8;
    private javax.swing.JCheckBox MediumSize;
    private javax.swing.JCheckBox MediumSize1;
    private javax.swing.JCheckBox MediumSize2;
    private javax.swing.JCheckBox MediumSize3;
    private javax.swing.JCheckBox MediumSize4;
    private javax.swing.JCheckBox MediumSize6;
    private javax.swing.JCheckBox MediumSize7;
    private javax.swing.JCheckBox MediumSize8;
    private javax.swing.JCheckBox SmallSize;
    private javax.swing.JCheckBox SmallSize1;
    private javax.swing.JCheckBox SmallSize2;
    private javax.swing.JCheckBox SmallSize3;
    private javax.swing.JCheckBox SmallSize4;
    private javax.swing.JCheckBox SmallSize6;
    private javax.swing.JCheckBox SmallSize7;
    private javax.swing.JCheckBox SmallSize8;
    private javax.swing.JLabel coffeeName;
    private javax.swing.JLabel coffeeName1;
    private javax.swing.JLabel coffeeName2;
    private javax.swing.JLabel coffeeName3;
    private javax.swing.JLabel coffeeName4;
    private javax.swing.JLabel coffeeName6;
    private javax.swing.JLabel coffeeName7;
    private javax.swing.JLabel coffeeName8;
    private javax.swing.JLabel coffeePrice;
    private javax.swing.JLabel coffeePrice1;
    private javax.swing.JLabel coffeePrice2;
    private javax.swing.JLabel coffeePrice3;
    private javax.swing.JLabel coffeePrice4;
    private javax.swing.JLabel coffeePrice6;
    private javax.swing.JLabel coffeePrice7;
    private javax.swing.JLabel coffeePrice8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    // End of variables declaration//GEN-END:variables
}
